In [1]:
import numpy as np


In [2]:
bank_data = np.array([
    [1001, 12500, 720, 35, 5],
    [1002, 5400, 650, 20, 3],
    [1003, 9800, 700, 28, 4],
    [1004, 15000, 780, 40, 8],
    [1005, 3200, 600, 15, 2],
    [1006, 8700, 690, 25, 4],
    [1007, 4500, 640, 18, 3],
    [1008, 20000, 820, 50, 10],
    [1009, 7600, 710, 30, 6],
    [1010, 6100, 670, 22, 3]
])

In [ ]:
Question 1: Array Creation and Manipulation

In [26]:
# Q1.1: Create a 4x4 identity matrix using np.eye()
identity_matrix = np.eye(4)
print(f"identity_matrix:\n{identity_matrix}")

identity_matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [32]:
#Q1.2: Create an array of 8 zeros using np.zeros()
zeros_array  = np.zeros(8)
print(f"zeros_array:\n{zeros_array}")

zeros_array:
[0. 0. 0. 0. 0. 0. 0. 0.]


In [36]:
#Q1.3: Create an array of 6 ones using np.ones()
ones_array = np.ones(6)
print(f"ones_array:\n{ones_array}")

ones_array:
[1. 1. 1. 1. 1. 1.]


In [38]:
#Q1.4: Create an array with values from 0 to 15 using np.arange()
arange_array = np.arange(16)
print(f"arange_array:\n{arange_array}")


arange_array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [40]:
#Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
linspace_array = np.linspace(0,100,8)
print(f"linspace_array:\n{linspace_array}")


linspace_array:
[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [ ]:
Question 2: Array Attributes and Information

In [54]:
#Q2.1: What is the shape of the banking_data array?
shape_of_bank_data = bank_data.shape
print(f"shape of bank data:\n{shape_of_bank_data}")

AttributeError: 'tuple' object has no attribute 'shape'

In [55]:
shape_of_bank_data = bank_data.shape
print(f"shape of bank data:\n{shape_of_bank_data}")

AttributeError: 'tuple' object has no attribute 'shape'

In [56]:
import numpy as np

bank_data = np.array([
    [1001,12500,720,35,5],
    [1002,5400,650,20,3],
    [1003,9800,700,28,4],
    [1004,15000,780,40,8],
    [1005,3200,600,15,2],
    [1006,8700,690,25,4],
    [1007,4500,640,18,3],
    [1008,20000,820,50,10],
    [1009,7600,710,30,6],
    [1010,6100,670,22,3]
])

In [57]:
shape_of_bank_data = bank_data.shape
print(f"shape of bank data:\n{shape_of_bank_data}")

shape of bank data:
(10, 5)


In [59]:
#Q2.2: What is the data type of the banking_data array?

dtype_of_bank_data = bank_data.dtype
print(f"dtype of bank data:\n{dtype_of_bank_data}")

dtype of bank data:
int64


In [ ]:
#Q2.3: What is the size (total number of elements) of the banking_data array?
total_elements = bank_data.size
print(f"total_elements of bank data:\n{total_elements}")


total_elements of bank data:
50


In [67]:
#Q2.4: What is the number of dimensions of the banking_data array?
number_dimension = bank_data.ndim
print(f"number_dimension of bank data:\n{number_dimension}")

number_dimension of bank data:
2


In [68]:
#Q2.5: What is the memory size of the banking_data array in bytes?
memory_size = bank_data.nbytes
print(f"memory_size of bank data:\n{memory_size}")

memory_size of bank data:
400


In [ ]:
Question 3: Indexing and Slicing

In [69]:
#Q3.1: Extract the first row of banking_data
first_row = bank_data[0]
print(f"first_row:\n{first_row}")


first_row:
[ 1001 12500   720    35     5]


In [75]:
#Q3.2: Extract the last row of banking_data
last_row = bank_data[9]
print(f"last_row:\n{last_row}")

last_row:
[1010 6100  670   22    3]


In [81]:
#Q3.3: Extract the Account_Balance column (column index 1)
account_balance_column =bank_data[:,1]
print(f"account_balance_column:\n{account_balance_column}")

account_balance_column:
[12500  5400  9800 15000  3200  8700  4500 20000  7600  6100]


In [82]:
#Q3.4: Extract the first 4 rows and first 3 columns
first_rows_first_columns = bank_data[:4,:3]
print(f"first_rows_first_columns:\n{first_rows_first_columns}")

first_rows_first_columns:
[[ 1001 12500   720]
 [ 1002  5400   650]
 [ 1003  9800   700]
 [ 1004 15000   780]]


In [83]:
#Q3.5: Extract rows 3 to 7 (inclusive)
data_set = bank_data[3:8]
print(f"data_set:\n{data_set}")


data_set:
[[ 1004 15000   780    40     8]
 [ 1005  3200   600    15     2]
 [ 1006  8700   690    25     4]
 [ 1007  4500   640    18     3]
 [ 1008 20000   820    50    10]]


In [ ]:
Question 4: Mathematical Operations

In [85]:
# Q4.1: Calculate the sum of all account balances
account_balance = bank_data[:,1]
total_balance = np.sum(account_balance)
print(f"total_balance:\n{total_balance}")



total_balance:
92800


In [86]:
#Q4.2: Calculate the mean account balance
mean_balance = np.mean(account_balance)
print(f"mean_balance:\n{mean_balance}")

mean_balance:
9280.0


In [ ]:
#Q4.3:Q4.3: Calculate the standard deviation of account balances 

standard_deviation = np.std(account_balance)
print(f"standard_deviation:\n{standard_deviation}")

standard_deviation:
4964.030620372924


In [96]:
#Q4.4: Calculate the variance of account balances
variance = np.var(account_balance)
print(f"variance:\n{variance}")

variance:
24641600.0


In [97]:
#Q4.5: Calculate the median account balance
median_balance = np.median(account_balance)
print(f"median_balance:\n{median_balance}")

median_balance:
8150.0


In [ ]:
Question 5: Statistical Functions

In [103]:
#Q5.1: Find the minimum and maximum account balances
min_balance = np.min(account_balance)
max_balance = np.max(account_balance)
print(f"min_balance:\n{min_balance}")
print(f"max_balance:\n{max_balance}")


min_balance:
3200
max_balance:
20000


In [104]:
#Q5.2: Find the minimum and maximum credit scores
min_credit_score = np.min(bank_data[:,2])
max_credit_score = np.max(bank_data[:,2])
print(f"min_credit_score:\n{min_credit_score}")
print(f"max_credit_score:\n{max_credit_score}")

min_credit_score:
600
max_credit_score:
820


In [105]:
#Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
percentile = np.percentile(account_balance, [25,50,75])
print(f"percentile:\n{percentile}")


percentile:
[ 5575.  8150. 11825.]


In [106]:
#Q5.4: Calculate the correlation between account balance and credit score
correlation = np.corrcoef(account_balance, bank_data[:,2])
print(f"correlation:\n{correlation}")

correlation:
[[1.         0.96978537]
 [0.96978537 1.        ]]


In [107]:
#Q5.5: Calculate the covariance between account balance and credit score
covariance = np.cov(account_balance, bank_data[:,2])
print(f"covariance:\n{covariance}")

covariance:
[[2.73795556e+07 3.31288889e+05]
 [3.31288889e+05 4.26222222e+03]]


In [ ]:
Question 6: Array Reshaping and Manipulation

In [108]:
#Q6.1: Reshape the banking_data to 5 rows × 10 columns
reshape_data = bank_data.reshape(5,10)
print(f"reshape_data:\n{reshape_data}")

reshape_data:
[[ 1001 12500   720    35     5  1002  5400   650    20     3]
 [ 1003  9800   700    28     4  1004 15000   780    40     8]
 [ 1005  3200   600    15     2  1006  8700   690    25     4]
 [ 1007  4500   640    18     3  1008 20000   820    50    10]
 [ 1009  7600   710    30     6  1010  6100   670    22     3]]


In [109]:
#Q6.2: Flatten the banking_data to a 1D array
flatten_data = bank_data.flatten()
print(f"flatten_data:\n{flatten_data}")

flatten_data:
[ 1001 12500   720    35     5  1002  5400   650    20     3  1003  9800
   700    28     4  1004 15000   780    40     8  1005  3200   600    15
     2  1006  8700   690    25     4  1007  4500   640    18     3  1008
 20000   820    50    10  1009  7600   710    30     6  1010  6100   670
    22     3]


In [114]:
#Q6.3: Transpose the banking_data
transpose_data = bank_data.T
print(f"transpose_data:\n{transpose_data}")

transpose_data:
[[ 1001  1002  1003  1004  1005  1006  1007  1008  1009  1010]
 [12500  5400  9800 15000  3200  8700  4500 20000  7600  6100]
 [  720   650   700   780   600   690   640   820   710   670]
 [   35    20    28    40    15    25    18    50    30    22]
 [    5     3     4     8     2     4     3    10     6     3]]


In [115]:
#Q6.4: Split the banking_data into 2 equal parts vertically
split_data = np.vsplit(bank_data,2)
print(f"split_data:\n{split_data}")

split_data:
[array([[ 1001, 12500,   720,    35,     5],
       [ 1002,  5400,   650,    20,     3],
       [ 1003,  9800,   700,    28,     4],
       [ 1004, 15000,   780,    40,     8],
       [ 1005,  3200,   600,    15,     2]]), array([[ 1006,  8700,   690,    25,     4],
       [ 1007,  4500,   640,    18,     3],
       [ 1008, 20000,   820,    50,    10],
       [ 1009,  7600,   710,    30,     6],
       [ 1010,  6100,   670,    22,     3]])]


In [124]:
#Q6.5: Split the banking_data into 2 equal parts horizontally
split_data_horizontal = np.array_split(bank_data,2,axis=1)
print(f"split_data_horizontal:\n{split_data_horizontal}")


split_data_horizontal:
[array([[ 1001, 12500,   720],
       [ 1002,  5400,   650],
       [ 1003,  9800,   700],
       [ 1004, 15000,   780],
       [ 1005,  3200,   600],
       [ 1006,  8700,   690],
       [ 1007,  4500,   640],
       [ 1008, 20000,   820],
       [ 1009,  7600,   710],
       [ 1010,  6100,   670]]), array([[35,  5],
       [20,  3],
       [28,  4],
       [40,  8],
       [15,  2],
       [25,  4],
       [18,  3],
       [50, 10],
       [30,  6],
       [22,  3]])]


In [ ]:
Question 7: Logical Operations and Filtering

In [139]:
#Q7.1: Find customers with account balance greater than $100,000
customer_account_balance = bank_data [:,2] > 100000
print(customer_account_balance)

[False False False False False False False False False False]


In [140]:
#Q7.2: Find customers with credit score greater than 800
customer_credit_score = bank_data [:,2] > 800
print(f"customer_credit_score:\n{customer_credit_score}")


customer_credit_score:
[False False False False False False False  True False False]


In [143]:
#Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
transaction_count = bank_data [:,2] > 50 
credit_score = bank_data  [:,2] < 750
print(f"transaction_count:\n{transaction_count}")
print(f"credit_score:\n{credit_score}")


transaction_count:
[ True  True  True  True  True  True  True  True  True  True]
credit_score:
[ True  True  True False  True  True  True False  True  True]


In [148]:
#Q7.4: Count how many customers have account balance between $10,000 and $100,000
customer_account_balance = (bank_data [:,2] > 10000) & (bank_data[:,2] < 100000)
print(f"customer_account_balance:\n{customer_account_balance}")

customer_account_balance:
[False False False False False False False False False False]


In [150]:
#Q7.5: Find the index of the customer with the highest credit score
customer_credit_score = bank_data  [:,2] > 10000
print(f"customer_credit_score:\n{customer_credit_score}")

customer_credit_score:
[False False False False False False False False False False]


In [ ]:
Question 8: Sorting and Searching

In [162]:
#Q8.1: Sort the banking_data by account balance (ascending)
sort_data = bank_data[bank_data [:,2].argsort()]
print(f"sort_data:\n{sort_data}")

sort_data:
[[ 1005  3200   600    15     2]
 [ 1007  4500   640    18     3]
 [ 1002  5400   650    20     3]
 [ 1010  6100   670    22     3]
 [ 1006  8700   690    25     4]
 [ 1003  9800   700    28     4]
 [ 1009  7600   710    30     6]
 [ 1001 12500   720    35     5]
 [ 1004 15000   780    40     8]
 [ 1008 20000   820    50    10]]


In [174]:
#Q8.2: Sort the banking_data by credit score (descending)
sorted_bank_data = bank_data[np.argsort(bank_data[:,2])[::-1]]
print(f"bank data sorted by credit score(descending):\n{sorted_bank_data}")

bank data sorted by credit score(descending):
[[ 1008 20000   820    50    10]
 [ 1004 15000   780    40     8]
 [ 1001 12500   720    35     5]
 [ 1009  7600   710    30     6]
 [ 1003  9800   700    28     4]
 [ 1006  8700   690    25     4]
 [ 1010  6100   670    22     3]
 [ 1002  5400   650    20     3]
 [ 1007  4500   640    18     3]
 [ 1005  3200   600    15     2]]


In [3]:
import numpy as np

In [4]:

bank_data = np.array([
    [1001, 12500, 720, 35, 5],
    [1002, 5400, 650, 20, 3],
    [1003, 9800, 700, 28, 4],
    [1004, 15000, 780, 40, 8],
    [1005, 3200, 600, 15, 2],
    [1006, 8700, 690, 25, 4],
    [1007, 4500, 640, 18, 3],
    [1008, 20000, 820, 50, 10],
    [1009, 7600, 710, 30, 6],
    [1010, 6100, 670, 22, 3]
])

In [5]:
#Q8.3: Find the indices that would sort the array by years active
indices_sort_by_years_active = bank_data[:,3].argsort()
print(f"indices_sort_by_years_active:\n{indices_sort_by_years_active}") 


indices_sort_by_years_active:
[4 6 1 9 5 2 8 0 3 7]


In [11]:
#Q8.4: Find the customer with the second highest account balance
second_higest_account_balance = np.argsort(bank_data[:,1])[::-1][1]
print(f"second_higest_account_balance:\n{second_higest_account_balance}")

second_higest_account_balance:
3


In [26]:
#Q8.5: Find the customer with the lowest transaction count
lowest_transaction_count = np.argmin(bank_data[:,3])
print(f"lowest_tansaction_count:\n{lowest_transaction_count}")


lowest_tansaction_count:
4


In [ ]:
Question 9: Mathematical Functions

In [22]:
#Q9.1: Calculate the absolute values of all elements
absolite_values_of_all_element = np.abs(bank_data)
print(f"absolute_values_of_all_element:\n{absolite_values_of_all_element}")

absolute_values_of_all_element:
[[ 1001 12500   720    35     5]
 [ 1002  5400   650    20     3]
 [ 1003  9800   700    28     4]
 [ 1004 15000   780    40     8]
 [ 1005  3200   600    15     2]
 [ 1006  8700   690    25     4]
 [ 1007  4500   640    18     3]
 [ 1008 20000   820    50    10]
 [ 1009  7600   710    30     6]
 [ 1010  6100   670    22     3]]


In [24]:
#Q9.2: Calculate the square root of all account balances
square_root_of_all_account_balance =  np.sqrt(bank_data[:,1])
print(f"square_root_of_all_account_balance:\n{square_root_of_all_account_balance}")

square_root_of_all_account_balance:
[111.80339887  73.48469228  98.99494937 122.47448714  56.56854249
  93.27379053  67.08203932 141.42135624  87.17797887  78.10249676]


In [38]:
#Q9.3: Calculate the square of all credit scores
square_of_all_credit_scores = np.sqrt(bank_data[:,1])
print(f"square_of_all_credit_scores:\n{square_of_all_credit_scores}")

square_of_all_credit_scores:
[111.80339887  73.48469228  98.99494937 122.47448714  56.56854249
  93.27379053  67.08203932 141.42135624  87.17797887  78.10249676]


In [42]:
#Q9.4: Calculate the exponential of all transaction counts
transaction_counts = np.exp(bank_data[:,1] / 10000)
print(f"transaction_counts:\n{transaction_counts}")

transaction_counts:
[3.49034296 1.71600686 2.66445624 4.48168907 1.37712776 2.38691085
 1.56831219 7.3890561  2.13827622 1.8404314 ]


In [46]:
#Q9.5: Calculate the natural logarithm of all account balances
natural_logarithm_of_all_account_balancce = np.log(bank_data[:,1]) 
print(f"natural_logarithm_of_all_account_balancce:\n{natural_logarithm_of_all_account_balancce}")

natural_logarithm_of_all_account_balancce:
[9.43348392 8.59415423 9.19013766 9.61580548 8.07090609 9.0710783
 8.41183268 9.90348755 8.93590353 8.71604405]


In [ ]:
Question 10: Advanced Operations

In [54]:
#Q10.1: Calculate the cumulative sum of account balances
cumulative_sum_of_account_balance = np.cumsum (bank_data[:,1])
print(f"cumulative_sum_of_account_balance:\n{cumulative_sum_of_account_balance}")


cumulative_sum_of_account_balance:
[12500 17900 27700 42700 45900 54600 59100 79100 86700 92800]


In [56]:
#Q10.2: Calculate the cumulative product of transaction counts
tansaction_counts = np.cumprod(bank_data[:,4])
print(f"tansaction_counts:\n{tansaction_counts}")


tansaction_counts:
[      5      15      60     480     960    3840   11520  115200  691200
 2073600]


In [57]:
#Q10.3: Calculate the difference between consecutive account balances
consecutive_account_balance = np.diff(bank_data[:,1])
print(f"consecutive_accpunt_balance:\n{consecutive_account_balance}")


consecutive_accpunt_balance:
[ -7100   4400   5200 -11800   5500  -4200  15500 -12400  -1500]


In [59]:
#Q10.4: Calculate the gradient of account balances
gradient_of_account_balance = np.gradient(bank_data[:,1])
print(f"gradient_of_account_balance:\n{gradient_of_account_balance}")

gradient_of_account_balance:
[-7100. -1350.  4800. -3300. -3150.   650.  5650.  1550. -6950. -1500.]


In [61]:
#Q10.5: Calculate the histogram of account balances with 5 bins
histogram_of_account_balance = np.histogram(bank_data[:,1],bins = 5)
print(f"histogram_of_account_balance:\n{histogram_of_account_balance}")

histogram_of_account_balance:
(array([4, 3, 1, 1, 1]), array([ 3200.,  6560.,  9920., 13280., 16640., 20000.]))


In [ ]:
Question 11: Random Numbers and Simulation

In [71]:
#Q11.1: Generate 6 random integers between 1 and 1000
random_integers = np.random.randint(1,1000,6)
print(f"random_integers:\n{random_integers}")

random_integers:
[243 971 941 873 862 487]


In [77]:
#Q11.2: Generate 6 random floats between 0 and 1
random_floats = np.random.uniform(0,1,6)
print(f"random_floats:\n{random_floats}")

random_floats:
[0.1278186  0.53327437 0.03535805 0.84056511 0.6988643  0.70121975]


In [78]:
#Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
normal_distribution = np.random.normal(700,1000)
print(f"normal_distribution:\n{normal_distribution}")



normal_distribution:
-112.34864300718448


In [80]:
#Q11.4: Shuffle the banking_data rows randomly
shuffle = np.random.randint(bank_data[:,1])
print(f"shuffle:\n{shuffle}")

shuffle:
[  969  5173   692  5421  2790  7337   364 14688  3394  1378]


In [83]:
#Q11.5: Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
random_numbers = np.random.rand(4)
print(f"random_numbers:\n{random_numbers}")

random_numbers:
[0.69646919 0.28613933 0.22685145 0.55131477]


In [ ]:
Question 12: Linear Algebra Operations

In [ ]:
#Q12.1: Calculate the dot product of account balance and credit score columns

product = np.dot(bank_data[:,1], bank_data[:,2])
print(f"product_of_account_balance_and_credit_score:\n{product}")


product_of_account_balance_and_credit_score:
67756000


In [113]:
#Q12.2: Calculate the cross product of first two rows
cross_product_of_first_two_rows = np.cross(bank_data[0, :3], bank_data[1, :3])
print(f"cross_product_of_first_two_rows:\n{cross_product_of_first_two_rows}")

cross_product_of_first_two_rows:
[ 4237000    70790 -7119600]


In [114]:
#Q12.3: Calculate the norm (magnitude) of the account balance column
norm_account_balance = np.linalg.norm(bank_data[:,1])
print(f"norm_of_account_balance:\n{norm_account_balance}")


norm_of_account_balance:
33280.62499413134


In [120]:
#Q12.4: Create a 3x3 matrix and calculate its determinant
martix = np.array([[1,2,3],[4,5,6],[7,8,9]])
determinant = np.linalg.det(martix)
print(determinant)

0.0


In [130]:
#Q12.5: Calculate the inverse of the 3x3 matrix
import numpy as np
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
inverse_matrix = np.linalg.inv(matrix)
print(f"matrix:\n{matrix}")
print(f"inverse_matrix:\n{inverse_matrix}")

LinAlgError: Singular matrix

In [ ]:
import numpy as np

# Create a 3x3 matrix
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,10]])
inverse_matrix = np.linalg.inv(matrix)
print(f"matrix:\n{matrix}")
print(f"inverse_matrix:\n{inverse_matrix}")


matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
inverse_matrix:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [ ]:
Question 13: String Operations

In [132]:
#Q13.1: Convert all customer IDs to strings
customer_ids_string = bank_data[:,0].astype(str)
print(f"cusotomer_ids_string:\n{customer_ids_string}")

cusotomer_ids_string:
['1001' '1002' '1003' '1004' '1005' '1006' '1007' '1008' '1009' '1010']


In [133]:
#Q13.2: Check if any customer ID contains '100'
customer_ids_str = bank_data[:,0].astype(str)
check_100 = np.char.find(customer_ids_str, '100') >= 0
print(f"contains_100:\n{check_100}")


contains_100:
[ True  True  True  True  True  True  True  True  True False]


In [134]:
#Q13.3: Convert all customer IDs to uppercase (if they were strings)
customer_ids_str = bank_data[:,0].astype(str)
customer_ids_upper = np.char.upper(customer_ids_str)
print(f"customer_ids_upper:\n{customer_ids_upper}")


customer_ids_upper:
['1001' '1002' '1003' '1004' '1005' '1006' '1007' '1008' '1009' '1010']


In [135]:
#Q13.4: Count the length of each customer ID string
customer_ids_str = bank_data[:,0].astype(str)
length_of_ids = np.char.str_len(customer_ids_str)
print(f"length_of_customer_ids:\n{length_of_ids}")


length_of_customer_ids:
[4 4 4 4 4 4 4 4 4 4]


In [136]:
#Q13.5: Replace '100' with 'CUST' in customer IDs
customer_ids_str = bank_data[:,0].astype(str)
updated_customer_ids = np.char.replace(customer_ids_str, '100', 'CUST')
print(f"updated_customer_ids:\n{updated_customer_ids}")


updated_customer_ids:
['CUST1' 'CUST2' 'CUST3' 'CUST4' 'CUST5' 'CUST6' 'CUST7' 'CUST8' 'CUST9'
 '1010']


In [ ]:
Question 14: Date and Time Operations

In [149]:
#Q14.1: Convert years active to months

years_active = bank_data[:,4]
months_active = years_active*12
print(f"months_active:\n{months_active}")


months_active:
[ 60  36  48  96  24  48  36 120  72  36]


In [151]:
#Q14.2: Calculate the average years active

years_active = bank_data[:,4]
avg_years = np.mean(years_active)
print(avg_years)

4.8


In [162]:
#Q14.3: Find customers who have been active for more than 5 years
customer_ids = bank_data[:,0]
years_active = bank_data[:,4]
customer_more_than_5 = customer_ids[years_active > 5]
print(customer_more_than_5)



[1004 1008 1009]


In [163]:
#Q14.4: Calculate the total time all customers have been active (in years)
years_active = bank_data[:,4]
total_years = np.sum(years_active)
print(total_years)

48


In [164]:
#Q14.5: Find the customer with the shortest time active
years_active = bank_data[:,4]
min_index = np.argmin(years_active)
shortest_customer = customer_ids[min_index]
print(shortest_customer)

1005


In [ ]:
Question 15: Advanced Array Operations

In [169]:
#Q15.1: Apply a function to calculate 5% interest on all account balances
def interest(balance):
    return balance * 0.05
account_balance = bank_data[:,1]
interest_amount = interest(account_balance)
print(interest_amount)


[ 625.  270.  490.  750.  160.  435.  225. 1000.  380.  305.]


In [170]:
#Q15.2: Use np.where to categorize customers by balance ranges
import numpy as np
balances = bank_data[:, 2]
balance_category = np.where(balances < 50000, "Low",
                    np.where(balances <= 100000, "Medium", "High"))
print(balance_category)

['Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low' 'Low']


In [172]:
#Q15.3: Use np.select to categorize customers by credit score ranges
import numpy as np
credit_scores = bank_data[:, 3].astype(int)
conditions = [
    credit_scores < 600,
    (credit_scores >= 600) & (credit_scores <= 700),
    credit_scores > 700
]
choices = ["Poor", "Average", "Good"]
credit_category = np.select(conditions, choices, default="Unknown")
print(credit_category)

['Poor' 'Poor' 'Poor' 'Poor' 'Poor' 'Poor' 'Poor' 'Poor' 'Poor' 'Poor']


In [173]:
#Q15.4: Use np.piecewise to apply different interest rates based on balance
import numpy as np
balances = bank_data[:, 2]
interest = np.piecewise(
    balances,
    [balances < 50000, (balances >= 50000) & (balances <= 100000), balances > 100000],
    [lambda x: x * 0.03, lambda x: x * 0.05, lambda x: x * 0.07]
)
print(interest)

[21 19 21 23 18 20 19 24 21 20]


In [174]:
#Q15.5: Use np.apply_along_axis to calculate the sum of each row
import numpy as np
row_sum = np.apply_along_axis(np.sum, axis=1, arr=bank_data)
print(row_sum)

[14261  7075 11535 16832  4822 10425  6168 21888  9355  7805]


In [ ]:
Question 16: Array Concatenation and Stacking

In [181]:
#Q16.1: Concatenate two arrays horizontally using np.hstack()
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
result = np.hstack([a,b])
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [183]:
#Q16.2: Concatenate two arrays vertically using np.vstack()
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
result = np.vstack([a,b])
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [184]:
#Q16.3: Concatenate arrays along a specific axis using np.concatenate()
result = np.concatenate((a,b),axis=1)
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [185]:
#Q16.4: Stack arrays depth-wise using np.dstack()
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
result = np.dstack([a,b])
print(result)


[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [187]:
#Q16.5: Create a column stack using np.column_stack()
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
result = np.column_stack([a,b])
print(result)


[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
Question 17: Array Splitting Operations

In [193]:
#Q17.1: Split an array into 3 equal parts using np.split()
arr = np.array([10,20,30,40,50,60])
result = np.split(arr,3)
print(result)


[array([10, 20]), array([30, 40]), array([50, 60])]


In [ ]:
#Q17.2: Split an array at specific indices using np.split()
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])
result = np.split(arr, [2, 4])
print(result)


[array([10, 20]), array([30, 40]), array([50, 60])]


In [205]:
##Q17.3: Split an array horizontally using np.hsplit()
arr = np.array([[1,2,3,4],
                [5,6,7,8]])
result = np.hsplit(arr, 2)
print(result)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [206]:
#Q17.4: Split an array vertically using np.vsplit()
arr = np.array([[1,2,3,4],
                [5,6,7,8]])
result = np.vsplit(arr, 2)
print(result)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [210]:
#Q17.5: Split an array into equal chunks using np.array_split()
arr = np.array([10,20,30,40,50,60,70])
result = np.array_split(arr, 3)
print(result)

[array([10, 20, 30]), array([40, 50]), array([60, 70])]


In [ ]:
Question 18: Array Repetition and Tiling


In [211]:
#Q18.1: Repeat each element of an array 3 times using np.repeat()
arr = np.array([1,2,3])
result = np.tile(arr, 3)
print(result)

[1 2 3 1 2 3 1 2 3]


In [212]:
#Q18.2: Repeat an entire array 2 times using np.tile()
arr = np.array([1,2,3])
result = np.tile(arr, 2)
print(result)

[1 2 3 1 2 3]


In [215]:
#Q18.3: Repeat a 2D array using np.tile()
arr = np.array([[1,2],
               [3,4]])
result = np.tile(arr, (2,2))
print(result)

[[1 2 1 2]
 [3 4 3 4]
 [1 2 1 2]
 [3 4 3 4]]


In [217]:
#Q18.4: Create a pattern using np.tile()
arr = np.array([1, 0])
result = np.tile(arr, (5))
print(result)

[1 0 1 0 1 0 1 0 1 0]


In [218]:
#Q18.5: Repeat elements with different counts using np.repeat()
arr = np.array([1, 2, 3])
result = np.repeat(arr, [1, 2, 3])
print(result)

[1 2 2 3 3 3]


In [ ]:
Question 19: Array Comparison and Logical Operations

In [219]:
#Q19.1: Compare two arrays for equality using np.array_equal()
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
result = np.array_equal(arr1, arr2)
print(result)


True


In [221]:
#Q19.2: Check if arrays are close using np.allclose()
arr1 = np.array([1.0, 2.0, 3.0])
arr2 = np.array([1.0, 2.000001, 2.999999])
result = np.allclose(arr1, arr2)
print(result)

True


In [222]:
#Q19.3: Apply logical AND operation between arrays
arr1 = np.array([True, False, True, False])
arr2 = np.array([True, True, False, False])
result = np.logical_and(arr1, arr2)
print(result)


[ True False False False]


In [223]:
#Q19.4: Apply logical OR operation between arrays
arr1 = np.array([True, False, True, False])
arr2 = np.array([True, True, False, False])
result = np.logical_or(arr1, arr2)
print(result)


[ True  True  True False]


In [224]:
#Q19.5: Apply logical NOT operation to an array
arr = np.array([True, False, True, False])
result = np.logical_not(arr)
print(result)

[False  True False  True]


In [ ]:
Question 20: Array Set Operations

In [225]:
#Q20.1: Find unique elements in an array using np.unique()
arr = np.array([1, 2, 2, 3, 4, 4, 5])
result = np.unique(arr)
print(result)

[1 2 3 4 5]


In [226]:
#Q20.2: Find the intersection of two arrays using np.intersect1d()
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])
result = np.intersect1d(arr1, arr2)
print(result)

[3 4 5]


In [227]:
#Q20.3: Find the union of two arrays using np.union1d()
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
result = np.union1d(arr1, arr2)
print(result)

[1 2 3 4 5 6]


In [228]:
#Q20.4: Find elements in first array but not in second using np.setdiff1d()
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 6])
result = np.setdiff1d(arr1, arr2)
print(result)

[1 2 5]


In [229]:
#Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
result = np.setxor1d(arr1, arr2)
print(result)

[1 2 5 6]
